apiVersion: v2
name: student-service
description: Student Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: base
    version: 1.0.0
    repository: file://../base

